apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-be-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cloud.google.com/load-balancer-type: "External"
spec:
  ingressClassName: platform-traefik
  rules:
    # HTTP API routing
    - host: sih-user-be.adityahota.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-be-service
                port:
                  number: 3000

    # WebSocket routing
    - host: sih-ws-user-be.adityahota.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-be-service
                port:
                  number: 3001
