apiVersion: v1
kind: Service
metadata:
  name: user-be-service
  labels:
    app: user-be
spec:
  selector:
    app: user-be
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: websocket
      port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
