apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-sm-credentials
            namespace: external-secrets
            key: accessKeyId
          secretAccessKeySecretRef:
            name: aws-sm-credentials
            namespace: external-secrets
            key: secretAccessKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sih-swaraj-user-be-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: sih-swaraj-user-be-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sih-swaraj-user-be-prod