apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ws-headers
  namespace: default
spec:
  headers:
    customRequestHeaders:
      Connection: "upgrade"
      Upgrade: "websocket"
    customResponseHeaders:
      Connection: "upgrade"
      Upgrade: "websocket"

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: user-be-ws-route
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`sih-ws-user-be.adityahota.online`)
      kind: Rule
      services:
        - name: user-be-service
          port: 3001
          sticky:
            cookie:
              name: ws-sticky
              secure: true
              httpOnly: true
      middlewares:
        - name: ws-headers
        - name: cors-headers
